name: Run Tests and Coverage

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change this to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov  # Add other dependencies here
          pip install -r requirements.txt || true  # If using a requirements file

      - name: Run tests with coverage
        run: |
          pytest --cov=my_project --cov-report=term-missing --cov-fail-under=80

