name: Run Tests and Coverage

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean up old package metadata
        run: rm -rf *.egg-info

      - name: Manually create egg-info
        run: python setup.py egg_info

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest pytest-cov
          pip install -e .

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=term-missing --cov-fail-under=96
